#!/usr/bin/env bash
set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RESET='\033[0m'
BOLD='\033[1m'

log_info()    { echo -e "${BLUE}ℹ${RESET}  $1"; }
log_success() { echo -e "${GREEN}✅${RESET} $1"; }
log_step()    { echo -e "${BOLD}${BLUE}▶${RESET} $1"; }

echo ""
echo -e "${BOLD}🗓️  Event Tracker — Local Dev Setup${RESET}"
echo "─────────────────────────────────────────"

bash scripts/devbox-guard.sh

# ─── Step 1: .env.local ───────────────────────────────────────────────────────
log_step "Checking .env.local..."

if [ ! -f ".env.local" ]; then
  AUTH_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")

  cat > .env.local << EOF
# Auto-generated by devbox run init — do not commit
TURSO_DATABASE_URL="file:./local.db"
TURSO_AUTH_TOKEN=""
AUTH_SECRET="${AUTH_SECRET}"
AUTH_URL="http://localhost:3000"
AUTH_GOOGLE_ID="your-google-client-id.apps.googleusercontent.com"
AUTH_GOOGLE_SECRET="your-google-client-secret"
DEMO_EMAIL="dev@localhost"
DEMO_PASSWORD="devpassword123"
EOF
  log_success ".env.local created"
else
  log_info ".env.local already exists — skipping"
fi

# ─── Step 2: pnpm install ─────────────────────────────────────────────────────
log_step "Installing dependencies..."

if [ ! -d "node_modules" ] || [ "package.json" -nt "node_modules/.modules.yaml" ]; then
  bash scripts/devbox-pnpm.sh install
  log_success "Dependencies installed"
else
  log_info "node_modules up to date — skipping"
fi

# ─── Step 3: DB schema ────────────────────────────────────────────────────────
log_step "Checking database..."

DB_URL_FOR_INIT="${TURSO_DATABASE_URL:-file:./local.db}"
if [[ "${DB_URL_FOR_INIT}" != file:* ]] && [[ -z "${TURSO_AUTH_TOKEN:-}" ]]; then
  log_info "TURSO_DATABASE_URL is remote but TURSO_AUTH_TOKEN is empty; using local.db for init"
  DB_URL_FOR_INIT="file:./local.db"
fi

SCHEMA_HASH_FILE=".devbox/.schema-hash"
SCHEMA_FILE="src/schema/schema.ts"

CURRENT_HASH=$(node -e "
  const crypto = require('crypto');
  const fs = require('fs');
  const content = fs.readFileSync('${SCHEMA_FILE}', 'utf8');
  console.log(crypto.createHash('md5').update(content).digest('hex'));
")

STORED_HASH=""
if [ -f "$SCHEMA_HASH_FILE" ]; then
  STORED_HASH=$(cat "$SCHEMA_HASH_FILE")
fi

if [ ! -f "local.db" ] || [ "$CURRENT_HASH" != "$STORED_HASH" ]; then
  log_step "Pushing schema to local.db..."
  TURSO_DATABASE_URL="$DB_URL_FOR_INIT" TURSO_AUTH_TOKEN="${TURSO_AUTH_TOKEN:-}" \
    bash scripts/devbox-pnpm.sh db:push
  mkdir -p .devbox
  echo "$CURRENT_HASH" > "$SCHEMA_HASH_FILE"
  log_success "Database ready → local.db"
else
  log_info "Schema unchanged — skipping db:push"
fi

# ─── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}✅ All done! Now run:${RESET}"
echo ""
echo -e "  ${BOLD}devbox run dev${RESET}   — start Next.js"
echo -e "  ${BOLD}pnpm db:studio${RESET}  — browse your local DB"
echo ""